name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: # Allow manual triggering

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          # Using environment variables for database credentials
          POSTGRES_USER: ${{ vars.TEST_DB_USER || 'postgres' }}
          POSTGRES_PASSWORD: ${{ vars.TEST_DB_PASSWORD || 'postgres' }} # pragma: allowlist secret
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest pytest-cov flake8
          pip install -e .

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Set up Python path and environment # pragma: allowlist secret
        run: |
          echo "PYTHONPATH=$PYTHONPATH:$(pwd)" >> $GITHUB_ENV
          echo "Current directory: $(pwd)"
          echo "Directory contents: $(ls -la)"
          # Create a testing config file with a placeholder secret key
          cat > testing_config.py << EOF
          # Database connection string for testing
          SQLALCHEMY_DATABASE_URI = 'postgresql://${{ vars.TEST_DB_USER || 'postgres' }}:${{ vars.TEST_DB_PASSWORD || 'postgres' }}@localhost:5432/test_db'
          # Test secret key (not for production)
          SECRET_KEY = 'ci_test_key_not_for_production' # pragma: allowlist secret
          TESTING = True
          WTF_CSRF_ENABLED = False
          EOF

      - name: Initialize database
        env:
          # Using environment variables for database connection
          DATABASE_URL: postgresql://${{ vars.TEST_DB_USER || 'postgres' }}:${{ vars.TEST_DB_PASSWORD || 'postgres' }}@localhost:5432/test_db
          SECRET_KEY: ci_test_key_not_for_production # pragma: allowlist secret
          FLASK_APP: run.py
          FLASK_ENV: testing
        run: |
          python -c "from capstone_blog import create_app, db; app = create_app('testing'); app.app_context().push(); db.create_all()"

      - name: Test with pytest
        env:
          # Using environment variables for database connection
          DATABASE_URL: postgresql://${{ vars.TEST_DB_USER || 'postgres' }}:${{ vars.TEST_DB_PASSWORD || 'postgres' }}@localhost:5432/test_db
          SECRET_KEY: ci_test_key_not_for_production # pragma: allowlist secret
          FLASK_APP: run.py
          FLASK_ENV: testing
          PYTHONPATH: ${{ github.workspace }}
        run: |
          python -c "import sys; print(sys.path)"
          python -c "import os; print(os.getcwd()); print(os.listdir('.'))"
          pytest -v --cov=capstone_blog tests/

  deploy:
    needs: test # Only deploy if tests pass
    if: github.ref == 'refs/heads/main' && github.event_name == 'push' # Only deploy on push to main
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.14
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "capstone-depot"
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          procfile: "web: gunicorn capstone_blog:create_app('production')"

      - name: Run database migrations
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          heroku run --app capstone-depot "flask db upgrade"
